### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by gautam1858** [Feryal/a3c-mujoco#1]
I am getting the following error could you please add requirement.txt file containing which all version I should use in detail , the error is something like this 

`    from torch._C import *
ImportError: numpy.core.multiarray failed to import`

**Comment by Feryal** [comment]
Seems like your numpy is too old. I've tested the code using version 1.13.0 on Linux Ubuntu 16.04. The code has similar dependancies as mujoco-py 1.50.1.

**Comment by gautam1858** [comment]
Yeah I have updated and the bumpy version is 1.13 only, I guess some error pytorch

**Comment by gautam1858** [comment]
ok thank you it worked
